apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  labels:
    app: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
        - name: mailhog
          image: "{{ .Values.mailhog.image }}"
          ports:
            - containerPort: 1025
            - containerPort: 8025
          resources:
            requests:
              memory: {{ .Values.mailhog.memory | default "64Mi" }}
            limits:
              memory: {{ .Values.mailhog.memory | default "64Mi" }}
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
spec:
  selector:
    app: mailhog
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
    - name: http
      port: 8025
      targetPort: 8025
