image:
  registry: ghcr.io/viney-3291
  tag: stable
  pullPolicy: IfNotPresent

jwtSecret: demo-secret-key-change-me

otelEndpoint: http://otel-collector:4318

services:
  api-gateway:
    port: 8080
    memory: 150Mi
    env:
      - name: OTEL_SERVICE_NAME
        value: api-gateway
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector:4318

  auth-service:
    port: 4001
    memory: 150Mi
    env:
      - name: OTEL_SERVICE_NAME
        value: auth-service
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector:4318
      - name: JWT_SECRET
        valueFrom:
          secretKeyRef:
            name: shopfront-secrets
            key: jwt-secret
      - name: DATA_DIR
        value: /data
    persistence:
      enabled: true
      mountPath: /data
      size: 1Gi

  product-service:
    port: 4002
    memory: 64Mi
    env:
      - name: OTEL_SERVICE_NAME
        value: product-service
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector:4318

  cart-service:
    port: 4003
    memory: 64Mi
    env:
      - name: OTEL_SERVICE_NAME
        value: cart-service
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector:4318
      - name: REDIS_HOST
        value: redis
      - name: REDIS_PORT
        value: "6379"

  inventory-service:
    port: 4004
    memory: 64Mi
    env:
      - name: OTEL_SERVICE_NAME
        value: inventory-service
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector:4318

  order-service:
    port: 4005
    memory: 200Mi
    env:
      - name: OTEL_SERVICE_NAME
        value: order-service
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector:4318
      - name: DATA_DIR
        value: /data
      - name: INVENTORY_SERVICE_URL
        value: http://inventory-service:4004
      - name: PAYMENT_SERVICE_URL
        value: http://payment-service:4006
      - name: PRODUCT_SERVICE_URL
        value: http://product-service:4002
      - name: NOTIFICATION_SERVICE_URL
        value: http://notification-service:4010
      - name: CART_SERVICE_URL
        value: http://cart-service:4003
    persistence:
      enabled: true
      mountPath: /data
      size: 1Gi

  payment-service:
    port: 4006
    memory: 150Mi
    env:
      - name: OTEL_SERVICE_NAME
        value: payment-service
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector:4318

  shipping-service:
    port: 4007
    memory: 100Mi
    env:
      - name: OTEL_SERVICE_NAME
        value: shipping-service
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector:4318

  review-service:
    port: 4008
    memory: 100Mi
    env:
      - name: OTEL_SERVICE_NAME
        value: review-service
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector:4318
      - name: DATA_DIR
        value: /data
    persistence:
      enabled: true
      mountPath: /data
      size: 1Gi

  recommendation-service:
    port: 4009
    memory: 150Mi
    env:
      - name: OTEL_SERVICE_NAME
        value: recommendation-service
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector:4318
      - name: PRODUCT_SERVICE_URL
        value: http://product-service:4002

  notification-service:
    port: 4010
    memory: 150Mi
    env:
      - name: OTEL_SERVICE_NAME
        value: notification-service
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector:4318
      - name: EMAIL_SERVICE_URL
        value: http://email-service:4011

  email-service:
    port: 4011
    memory: 100Mi
    env:
      - name: OTEL_SERVICE_NAME
        value: email-service
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector:4318
      - name: SMTP_HOST
        value: mailhog
      - name: SMTP_PORT
        value: "1025"

  search-service:
    port: 4012
    memory: 64Mi
    env:
      - name: OTEL_SERVICE_NAME
        value: search-service
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector:4318
      - name: PRODUCT_SERVICE_URL
        value: http://product-service:4002

frontend:
  port: 80
  memory: 64Mi
  serviceType: LoadBalancer

redis:
  image: redis:7-alpine
  memory: 64Mi

mailhog:
  image: mailhog/mailhog:v1.0.1
  memory: 64Mi