apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopfront-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/viney-3291/Shopfront.git
    targetRevision: main
    path: k8s/helm/shopfront
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true