apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.registry }}/shopfront-frontend:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: {{ .Values.frontend.memory | default "64Mi" }}
            limits:
              memory: {{ .Values.frontend.memory | default "64Mi" }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: {{ .Values.frontend.serviceType }}
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
